[package]
name = "bitbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
leb128 = "0.2.5"

[dev-dependencies]
insta = { version = "1.41.1", features = ["yaml"] }
pretty_assertions = "1.3.0"
